#!/bin/sh
# =============================================================================
# install.sh — Susanin.Keenetic installer for KeeneticOS/Entware (Phase 1 draft)
#
# Responsibilities (per PLAN):
#   1. Collect device info (firmware version, arch, CPU/RAM).
#   2. Check required programs/component presence (opkg, iptables, ipset,
#      iproute2, /proc/net/nf_conntrack).
#   3. Auto-detect egress (VPN/WireGuard) interface and LAN interfaces; allow
#      override via --egress <ifname> and --lan <if,...>.
#   4. Ensure Entware package dependencies.
#   5. Backup current netfilter state (iptables-save, ip rule, routes).
#   6. Install files + init script; run first setup/reconcile.
#   7. Uninstall (--uninstall) stops service and removes managed objects.
#
# Read-only until you pass --install (or run `susanin-agent setup`).
# POSIX sh (busybox ash compatible). No bashisms.
# =============================================================================

set -eu

PREFIX=/opt
SUSANIN_DIR="$PREFIX/susanin"
CONF="$SUSANIN_DIR/etc/susanin.conf"
SERVICE="$PREFIX/etc/init.d/S94susanin"
AGENT="$SUSANIN_DIR/susanin-agent"

MODE=check
EGRESS=""
LAN=""
BACKUP=1

while [ $# -gt 0 ]; do
    case "$1" in
        --install) MODE=install ;;
        --uninstall) MODE=uninstall ;;
        --egress) EGRESS="$2"; shift ;;
        --lan) LAN="$2"; shift ;;
        --no-backup) BACKUP=0 ;;
        -h|--help)
            echo "Usage: $0 [--install|--uninstall] [--egress <if>] [--lan <if,...>] [--no-backup]"
            exit 0 ;;
        *) echo "unknown arg: $1" >&2; exit 1 ;;
    esac
    shift
done

SAY() { echo "[susanin] $*"; }

# ---------------------------------------------------------------------------
SAY "1. Device / firmware"
echo "  hostname : $(cat /proc/sys/kernel/hostname 2>/dev/null || echo n/a)"
echo "  kernel   : $(uname -r 2>/dev/null || echo n/a)"
echo "  uname    : $(uname -a 2>/dev/null || echo n/a)"
echo "  cpu      : $(awk -F: '/machine/{print $2}' /proc/cpuinfo 2>/dev/null | head -1 || echo n/a)"

echo "  firmware :"
for _f in /etc/ndm/version /etc/version /etc/firmware_release /etc/openwrt_release; do
    [ -r "$_f" ] && { echo "    $(_f)"; sed -n '1,5p' "$_f" 2>/dev/null | sed 's/^/      /'; }
done
if command -v opkg >/dev/null 2>&1; then
    echo "  opkg db  : $(opkg info busybox 2>/dev/null | awk '/Version/{print $2; exit}') (busybox)"
fi

# ---------------------------------------------------------------------------
SAY "2. Required programs/components"
for _t in opkg sh iptables ipset ip awk grep sed nft; do
    if command -v "$_t" >/dev/null 2>&1; then
        echo "  ok   $_t -> $(command -v $_t)"
    else
        echo "  MISS $_t"
    fi
done
if [ -r /proc/net/nf_conntrack ]; then
    echo "  ok   /proc/net/nf_conntrack ($(awk 'END{print NR" entries"}' /proc/net/nf_conntrack 2>/dev/null))"
else
    echo "  MISS /proc/net/nf_conntrack"
fi
if [ -d /opt/etc/init.d ]; then
    echo "  ok   Entware init.d present"
else
    echo "  MISS Entware init.d (Entware installed?)"
fi

# ---------------------------------------------------------------------------
SAY "3. Detect egress / LAN interfaces"
_vpn_detect() {
    # Prefer interfaces with a route table default that is NOT ppp0 and that
    # are WireGuard-like by name; fallback to configured/--egress.
    _cand=$(ip -o link show 2>/dev/null | awk -F': ' '{print $2}' | tr -d ':@"' \
        | grep -Ei '^(nwg|wg[0-9]|amnezia|vpn)' | head -1)
    [ -n "${_cand:-}" ] && { echo "$_cand"; return; }
    # fallback: a non-ppp0 default route device present in any table
    ip route show table all 2>/dev/null | awk '$1=="default"{print $3}' \
        | sed 's/dev //' | grep -Ev '^(ppp0|lo)$' | head -1
}
_lan_detect() {
    # Bridges carrying private IPv4
    for _br in br0 br1; do
        ip addr show "$_br" 2>/dev/null | grep -q 'inet ' && echo -n "${_br}"
    done
}

EGRESS="${EGRESS:-$(_vpn_detect)}"
[ -n "$EGRESS" ] || EGRESS=nwg0
echo "  egress (VPN) : $EGRESS"

LAN="${LAN:-$(_lan_detect)}"
[ -n "$LAN" ] || LAN=br0
echo "  lan ifaces   : $LAN"

# ---------------------------------------------------------------------------
SAY "4. Config (will be generated by 'susanin setup' in Phase 5)"
echo "  config path  : $CONF"
echo "  (Phase 1 draft: no config written yet)"

case "$MODE" in
    check)
        SAY "Read-only check done. To install: $0 --install"
        exit 0 ;;
    uninstall)
        SAY "Uninstall not implemented yet (Phase 7): stops service + removes managed objects."
        exit 2 ;;
esac

# ---------------------------------------------------------------------------
SAY "5. Backup current netfilter (before any change)"
if [ "$BACKUP" = 1 ]; then
    _bk="$SUSANIN_DIR/var/preinstall-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$_bk"
    [ -x /opt/sbin/iptables-save ] && /opt/sbin/iptables-save > "$_bk/iptables-save.txt" 2>/dev/null || true
    ip rule show > "$_bk/ip-rule.txt" 2>/dev/null || true
    ip route show table all > "$_bk/ip-route.txt" 2>/dev/null || true
    echo "  backup dir : $_bk"
fi

SAY "6. Deploy (Phase 1 draft — placeholder)"
echo "  agent binary : $AGENT"
echo "  init script  : $SERVICE"
echo "  Next Phase 5 will: write config, create table/rules via susanin-agent setup."

SAY "Done (draft). Full install logic lands in Phase 3-5."
